# Project
version=0.0.1

# Common
license=LGPL-3.0-only AND CC-BY-NC-SA-4.0 AND LicenseRef-To-Series-Third-Party-Music
modAuthor=joshmanisdabomb
homepage=https://to.jidb.net
sources=https://github.com/joshmanisdabomb/to-series
issues=https://github.com/joshmanisdabomb/to-series/issues

# Defaults
group = net.jidb.to
modId = to
modName = To Undefined
toBaseVersion = MISSING

# Gradle
org.gradle.jvmargs=-Xmx6G
org.gradle.daemon=false