[versions]
java = "25"
kotlin = "2.3.21"
moddev = "2.0.141"
loom = "1.16-SNAPSHOT"
dokka = "2.2.0"

minecraft = "26.1.2"
minecraftRange = "[26.1.2, 26.2)"

neoforge = "26.1.2.70-beta"
neoforgeRange = "[26.1.2.69, 26.2)"
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neoForm = "26.1.2-1"
kff = "6.2.0"
kffRange = "[6.2, )"

fabricLoader = "0.19.2"
fabricApi = "0.150.0+26.1.2"
fabricVersion = "0.150.0"
flk = "1.13.11+kotlin.2.3.21"

mixin = "0.8.5"
mixinExtras = "0.5.3"

techReborn = "5.0.0"

commonmark = "0.27.1"
modeshape = "5.4.1.Final"

[libraries]
minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }
fabricLoader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabricLoader" }
fabricApi = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabricApi" }
flk = { group = "net.fabricmc", name = "fabric-language-kotlin", version.ref = "flk" }
kff = { group = "thedarkcolour", name = "kotlinforforge-neoforge", version.ref = "kff" }
mixin = { group = "org.spongepowered", name = "mixin", version.ref = "mixin" }
mixinExtras-common = { group = "io.github.llamalad7", name = "mixinextras-common", version.ref = "mixinExtras" }
techReborn = { group = "teamreborn", name = "energy", version.ref = "techReborn" }
commonmark = { group = "org.commonmark", name = "commonmark", version.ref = "commonmark" }
commonmark-yaml = { group = "org.commonmark", name = "commonmark-ext-yaml-front-matter", version.ref = "commonmark" }
modeshape-common = { group = "org.modeshape", name = "modeshape-common", version.ref = "modeshape" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
moddev = { id = "net.neoforged.moddev", version.ref = "moddev" }
loom = { id = "net.fabricmc.fabric-loom", version.ref = "loom" }
