[versions]
java = "21"
kotlin = "2.3.10"
moddev = "2.0.140"
loom = "1.13-SNAPSHOT"
dokka = "1.9.20"

minecraft = "1.21.11"
minecraftRange = "[1.21.11, 1.22)"

# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment = "2025.12.20"
parchmentMC = "1.21.11"

neoforge = "21.11.38-beta"
neoforgeRange = "[21.11.37, 21.12)"
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neoForm = "1.21.11-20251209.172050"
kff = "6.1.0"
kffRange = "[6.1, )"

fabricLoader = "0.18.4"
fabricApi = "0.141.3+1.21.11"
fabricVersion = "0.141.3"
flk = "1.13.9+kotlin.2.3.10"
fabricModMenu = "17.0.0-beta.2"

mixin = "0.8.5"
mixinExtras = "0.5.3"

[libraries]
minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }
fabricLoader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabricLoader" }
fabricApi = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabricApi" }
flk = { group = "net.fabricmc", name = "fabric-language-kotlin", version.ref = "flk" }
kff = { group = "thedarkcolour", name = "kotlinforforge-neoforge", version.ref = "kff" }
mixin = { group = "org.spongepowered", name = "mixin", version.ref = "mixin" }
mixinExtras-common = { group = "io.github.llamalad7", name = "mixinextras-common", version.ref = "mixinExtras" }
fabricModMenu = { group = "com.terraformersmc", name = "modmenu", version.ref = "fabricModMenu" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
moddev = { id = "net.neoforged.moddev", version.ref = "moddev" }
loom = { id = "fabric-loom", version.ref = "loom" }