pluginManagement {
    repositories {
        maven { url = 'https://maven.fabricmc.net/' }
        maven { url = 'https://maven.architectury.dev/' }
        maven { url = 'https://files.minecraftforge.net/maven/' }
        gradlePluginPortal()
    }
}
plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.10.0'
}

rootProject.name = 'to_series'

include 'to_base:common'
include 'to_base:fabric'
include 'to_base:neoforge'
include 'to_sky_and_stars:common'
include 'to_sky_and_stars:fabric'
include 'to_sky_and_stars:neoforge'
