package net.jidb.to.base.api.gametest

import net.minecraft.core.Vec3i
import net.minecraft.gametest.framework.GameTestHelper
import net.minecraft.resources.Identifier
import net.minecraft.world.level.block.Blocks
import net.minecraft.world.level.block.Rotation
import net.minecraft.world.level.block.state.BlockState

/**
 * One game test: the code it runs, the scene it runs in, and the terms it is judged under.
 *
 * A game test is three separate things to the game - a function in a registry, a test instance in a data pack, and a structure file - which have to agree with one another by name.
 * Declaring one of these against a [net.jidb.to.base.pub.library.GameTestLibrary] produces all three, so a test is written once and named once.
 *
 * The scene defaults to a flat platform of [size] with a floor of [floor], generated by [net.jidb.to.base.data.pub.provider.GameTestStructureDataProvider] under the same name as the test.
 * A test that wants a scene built by hand names it in [structure] instead, in which case nothing is generated for it.
 *
 * @param size How large the generated platform is, counting its floor. Defaults to five by four by five, which is room enough for a three-block-long machine at its centre. Ignored where [structure] is set.
 * @param floor The state the bottom layer of the generated platform is filled with, or `null` for a platform of nothing but air. Defaults to polished andesite, as vanilla's own test structures use. Ignored where [structure] is set.
 * @param structure The structure the test is run in, or `null` to generate a platform for it. Defaults to `null`.
 * @param maxTicks How long the test may run for before it counts as failed. Defaults to 100.
 * @param setupTicks How long the test is left to settle before it starts, which is not counted against [maxTicks]. Defaults to 0.
 * @param required Whether the run as a whole fails when this test does. Defaults to `true`.
 * @param rotation How far the structure is turned before the test is run, which a test written against relative positions should not notice. Defaults to [Rotation.NONE].
 * @param manualOnly Whether the test is skipped unless it is asked for by name through the `/test` command. Defaults to `false`.
 * @param maxAttempts How many times the test may be run before it counts as failed. Defaults to 1.
 * @param requiredSuccesses How many of those attempts have to pass. Defaults to 1.
 * @param skyAccess Whether the scene is left open to the sky rather than being boxed in. Defaults to `false`.
 * @param padding How much empty space is left between this test and the next when a run lays them out side by side. Defaults to 0.
 * @param run The test itself, which is handed a [GameTestHelper] to act on the scene through and has to reach [GameTestHelper.succeed] to pass.
 * @since 1.0.0
 */
class ToGameTest(
    val size: Vec3i = Vec3i(5, 4, 5),
    val floor: BlockState? = Blocks.POLISHED_ANDESITE.defaultBlockState(),
    val structure: Identifier? = null,
    val maxTicks: Int = 100,
    val setupTicks: Int = 0,
    val required: Boolean = true,
    val rotation: Rotation = Rotation.NONE,
    val manualOnly: Boolean = false,
    val maxAttempts: Int = 1,
    val requiredSuccesses: Int = 1,
    val skyAccess: Boolean = false,
    val padding: Int = 0,
    val run: (helper: GameTestHelper) -> Unit,
) {

    /**
     * The structure this test is run in, which is the one it names or, failing that, one of its own generated under its own name.
     *
     * @param id The identifier the test itself is registered under.
     * @return The identifier of the structure.
     * @since 1.0.0
     */
    fun getStructure(id: Identifier) = structure ?: id

}
